// ============================================
// 示例衣橱 —— 空衣橱里点一下就能试搭配
// 没有照片，卡片会退化成配色块，不影响推荐
// ============================================
export const SAMPLE_ITEMS = [
  {
    name: '白色圆领 T 恤',
    category: 'top',
    colors: ['white'],
    seasons: ['spring', 'summer'],
    occasions: ['daily', 'date'],
    warmth: 1,
    tags: ['纯棉', '百搭'],
  },
  {
    name: '灰色条纹衬衫',
    category: 'top',
    colors: ['gray', 'white'],
    seasons: ['spring', 'autumn'],
    occasions: ['work', 'daily'],
    warmth: 2,
    tags: ['免烫'],
  },
  {
    name: '藏蓝针织衫',
    category: 'top',
    colors: ['blue'],
    seasons: ['autumn', 'winter'],
    occasions: ['work', 'daily'],
    warmth: 3,
    tags: ['羊毛'],
  },
  {
    name: '粉色卫衣',
    category: 'top',
    colors: ['pink'],
    seasons: ['autumn', 'spring'],
    occasions: ['daily', 'sport'],
    warmth: 3,
    tags: ['宽松'],
  },
  {
    name: '直筒牛仔裤',
    category: 'bottom',
    colors: ['denim'],
    seasons: ['spring', 'autumn', 'winter'],
    occasions: ['daily', 'date'],
    warmth: 3,
    tags: ['高腰'],
  },
  {
    name: '黑色西装裤',
    category: 'bottom',
    colors: ['black'],
    seasons: ['spring', 'autumn', 'winter'],
    occasions: ['work', 'formal'],
    warmth: 2,
    tags: ['垂坠'],
  },
  {
    name: '米色阔腿裤',
    category: 'bottom',
    colors: ['beige'],
    seasons: ['spring', 'summer'],
    occasions: ['daily', 'work'],
    warmth: 1,
    tags: ['垂感'],
  },
  {
    name: '墨绿半身裙',
    category: 'bottom',
    colors: ['green'],
    seasons: ['autumn'],
    occasions: ['date', 'work'],
    warmth: 2,
    tags: ['A 字'],
  },
  {
    name: '碎花连衣裙',
    category: 'dress',
    colors: ['pink', 'white'],
    seasons: ['summer'],
    occasions: ['date', 'daily'],
    warmth: 2,
    tags: ['雪纺'],
  },
  {
    name: '黑色小礼裙',
    category: 'dress',
    colors: ['black'],
    seasons: ['spring', 'autumn'],
    occasions: ['formal', 'date'],
    warmth: 2,
    tags: ['正装'],
  },
  {
    name: '米色风衣',
    category: 'outerwear',
    colors: ['beige'],
    seasons: ['spring', 'autumn'],
    occasions: ['daily', 'work'],
    warmth: 3,
    tags: ['防水'],
  },
  {
    name: '牛仔外套',
    category: 'outerwear',
    colors: ['denim'],
    seasons: ['spring', 'autumn'],
    occasions: ['daily', 'date'],
    warmth: 3,
    tags: ['水洗'],
  },
  {
    name: '黑色羽绒服',
    category: 'outerwear',
    colors: ['black'],
    seasons: ['winter'],
    occasions: ['daily', 'work'],
    warmth: 5,
    tags: ['防风'],
  },
  {
    name: '白色小白鞋',
    category: 'shoes',
    colors: ['white'],
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['daily', 'sport'],
    warmth: 1,
    tags: ['帆布'],
  },
  {
    name: '棕色乐福鞋',
    category: 'shoes',
    colors: ['brown'],
    seasons: ['spring', 'autumn'],
    occasions: ['work', 'formal', 'date'],
    warmth: 2,
    tags: ['皮'],
  },
  {
    name: '黑色短靴',
    category: 'shoes',
    colors: ['black'],
    seasons: ['autumn', 'winter'],
    occasions: ['daily', 'work', 'date'],
    warmth: 3,
    tags: ['皮'],
  },
  {
    name: '棕色托特包',
    category: 'bag',
    colors: ['brown'],
    seasons: [],
    occasions: ['work', 'daily'],
    warmth: 1,
    tags: ['能装电脑'],
  },
  {
    name: '米白色围巾',
    category: 'accessory',
    colors: ['beige'],
    seasons: ['winter', 'autumn'],
    occasions: ['daily'],
    warmth: 2,
    tags: ['羊绒'],
  },
]
